package iptables

import (
	"testing"
)

const sampleIptablesSave = `# Generated by iptables-save v1.8.9
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SEP-AAAAA - [0:0]
:KUBE-SEP-BBBBB - [0:0]
:KUBE-SEP-CCCCC - [0:0]
:KUBE-MARK-MASQ - [0:0]
-A KUBE-SERVICES -d 10.96.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https -> 10.0.0.1:6443" -j KUBE-SEP-AAAAA
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp -> 10.244.0.5:53" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-BBBBB
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp -> 10.244.0.6:53" -j KUBE-SEP-CCCCC
-A KUBE-SEP-AAAAA -s 10.0.0.1/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-AAAAA -p tcp -m comment --comment "default/kubernetes:https" -m tcp -j DNAT --to-destination 10.0.0.1:6443
-A KUBE-SEP-BBBBB -s 10.244.0.5/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-BBBBB -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.244.0.5:53
-A KUBE-SEP-CCCCC -s 10.244.0.6/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-CCCCC -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.244.0.6:53
COMMIT
`

func TestParseEndpoints(t *testing.T) {
	endpoints := parseEndpoints(sampleIptablesSave)

	if len(endpoints) != 3 {
		t.Fatalf("expected 3 endpoints, got %d", len(endpoints))
	}

	byChain := make(map[string]ServiceEndpoint)
	for _, ep := range endpoints {
		byChain[ep.ChainName] = ep
	}

	tests := []struct {
		chain       string
		podIP       string
		podPort     string
		parentChain string
	}{
		{"KUBE-SEP-AAAAA", "10.0.0.1", "6443", "KUBE-SVC-NPX46M4PTMTKRN6Y"},
		{"KUBE-SEP-BBBBB", "10.244.0.5", "53", "KUBE-SVC-ERIFXISQEP7F7OF4"},
		{"KUBE-SEP-CCCCC", "10.244.0.6", "53", "KUBE-SVC-ERIFXISQEP7F7OF4"},
	}

	for _, tt := range tests {
		ep, ok := byChain[tt.chain]
		if !ok {
			t.Errorf("chain %s not found", tt.chain)
			continue
		}
		if ep.PodIP != tt.podIP {
			t.Errorf("%s: PodIP = %q, want %q", tt.chain, ep.PodIP, tt.podIP)
		}
		if ep.PodPort != tt.podPort {
			t.Errorf("%s: PodPort = %q, want %q", tt.chain, ep.PodPort, tt.podPort)
		}
		if ep.ParentChain != tt.parentChain {
			t.Errorf("%s: ParentChain = %q, want %q", tt.chain, ep.ParentChain, tt.parentChain)
		}
	}
}

func TestParseEndpointsEmpty(t *testing.T) {
	endpoints := parseEndpoints("*nat\nCOMMIT\n")
	if len(endpoints) != 0 {
		t.Fatalf("expected 0 endpoints, got %d", len(endpoints))
	}
}

func TestParseEndpointsOrphanedChain(t *testing.T) {
	rules := `*nat
:KUBE-SEP-ORPHAN - [0:0]
-A KUBE-SEP-ORPHAN -p tcp -m tcp -j DNAT --to-destination 10.244.1.99:8080
COMMIT
`
	endpoints := parseEndpoints(rules)
	if len(endpoints) != 1 {
		t.Fatalf("expected 1 endpoint, got %d", len(endpoints))
	}
	ep := endpoints[0]
	if ep.PodIP != "10.244.1.99" {
		t.Errorf("PodIP = %q, want %q", ep.PodIP, "10.244.1.99")
	}
	if ep.ParentChain != "" {
		t.Errorf("ParentChain = %q, want empty (orphaned)", ep.ParentChain)
	}
}
