// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type EGhostBusterConnectionInfo struct {
	_         structs.HostLayout
	Pid       uint32
	_         [4]byte
	StartTime uint64
	Comm      [16]uint8
}

type EGhostBusterConnectionKey struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	_       [3]byte
}

// LoadEGhostBuster returns the embedded CollectionSpec for EGhostBuster.
func LoadEGhostBuster() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EGhostBusterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load EGhostBuster: %w", err)
	}

	return spec, err
}

// LoadEGhostBusterObjects loads EGhostBuster and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*EGhostBusterObjects
//	*EGhostBusterPrograms
//	*EGhostBusterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadEGhostBusterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadEGhostBuster()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// EGhostBusterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EGhostBusterSpecs struct {
	EGhostBusterProgramSpecs
	EGhostBusterMapSpecs
	EGhostBusterVariableSpecs
}

// EGhostBusterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EGhostBusterProgramSpecs struct {
	BpfReaper      *ebpf.ProgramSpec `ebpf:"bpf_reaper"`
	HandleSetState *ebpf.ProgramSpec `ebpf:"handle_set_state"`
	TcpV4Connect   *ebpf.ProgramSpec `ebpf:"tcp_v4_connect"`
}

// EGhostBusterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EGhostBusterMapSpecs struct {
	ConnTracker   *ebpf.MapSpec `ebpf:"conn_tracker"`
	SkInfoStorage *ebpf.MapSpec `ebpf:"sk_info_storage"`
	ZombieEvents  *ebpf.MapSpec `ebpf:"zombie_events"`
}

// EGhostBusterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EGhostBusterVariableSpecs struct {
}

// EGhostBusterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadEGhostBusterObjects or ebpf.CollectionSpec.LoadAndAssign.
type EGhostBusterObjects struct {
	EGhostBusterPrograms
	EGhostBusterMaps
	EGhostBusterVariables
}

func (o *EGhostBusterObjects) Close() error {
	return _EGhostBusterClose(
		&o.EGhostBusterPrograms,
		&o.EGhostBusterMaps,
	)
}

// EGhostBusterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadEGhostBusterObjects or ebpf.CollectionSpec.LoadAndAssign.
type EGhostBusterMaps struct {
	ConnTracker   *ebpf.Map `ebpf:"conn_tracker"`
	SkInfoStorage *ebpf.Map `ebpf:"sk_info_storage"`
	ZombieEvents  *ebpf.Map `ebpf:"zombie_events"`
}

func (m *EGhostBusterMaps) Close() error {
	return _EGhostBusterClose(
		m.ConnTracker,
		m.SkInfoStorage,
		m.ZombieEvents,
	)
}

// EGhostBusterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadEGhostBusterObjects or ebpf.CollectionSpec.LoadAndAssign.
type EGhostBusterVariables struct {
}

// EGhostBusterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadEGhostBusterObjects or ebpf.CollectionSpec.LoadAndAssign.
type EGhostBusterPrograms struct {
	BpfReaper      *ebpf.Program `ebpf:"bpf_reaper"`
	HandleSetState *ebpf.Program `ebpf:"handle_set_state"`
	TcpV4Connect   *ebpf.Program `ebpf:"tcp_v4_connect"`
}

func (p *EGhostBusterPrograms) Close() error {
	return _EGhostBusterClose(
		p.BpfReaper,
		p.HandleSetState,
		p.TcpV4Connect,
	)
}

func _EGhostBusterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed eghostbuster_x86_bpfel.o
var _EGhostBusterBytes []byte
